### ISSUE TITLE
Not downloading reviews (end code:500)

### ISSUE THREAD

**Issue by kmander** [aesuli/Amazon-downloader#7]
Command and response:

`perl downloadAmazonReviews.pl com B01KQIWHOW
`
`http://www.amazon.com/product-reviews/B01KQIWHOW/?ie=UTF8&showViewpoints=0&pageNumber=1&sortBy=bySubmissionDateDescending Downloaded 0 pages for product id B01KQIWHOW (end code:500)
`

Thoughts?

Thank you.

**Comment by comppaz** [comment]
I suppose this is due to the redirection of HTTP -> HTTPS. On Ubuntu 14.04 I had to: 

1. Install libssl-dev 
`sudo apt-get update && sudo apt-get install libssl-dev`

2. Provide an SSL Interface for LWP, thus I Installed the Crypt::SSLeay module: 
`sudo cpan Crypt::SSLeay`

3. Finally, edit the following line in **downloadAmazonReviews.pl** (Line 47):
`my $urlPart1 = "http://www.amazon.".$domain."/product-reviews/";` 
to
`my $urlPart1 = "https://www.amazon.".$domain."/product-reviews/";`

**Comment by CFLJacquet** [comment]
Changing 
> my $urlPart1 = "http://www.amazon.".$domain."/product-reviews/";
> to
> my $urlPart1 = "https://www.amazon.".$domain."/product-reviews/";

works, thanks comppaz !

Unfortunately the code neither creates a new folder nor downloads the html files... Any ideas?
I'm trying to download reviews of a product on amazon.co.uk

Thanks

**Comment by dfjeiwn** [comment]
Maybe you can try an **[Amazon downloader](https://streamfab.com/amazon-downloader.htm)**
